/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Beans.Historialc;
import Beans.Paciente;
import Controller.HistorialcController;
import Controller.PacienteController;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr Baltazar
 */
public class FrmHistorialc extends javax.swing.JFrame {

    private HistorialcController histcontroller = new HistorialcController();
    private DefaultTableModel dtmhistorial = new DefaultTableModel();
    private PacienteController pacicontroller = new PacienteController();
    
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form FrmHistorialc2
     */
    public FrmHistorialc() {
        
        this.setContentPane(fondo);
        
        initComponents();
        llenaTabla();
        listar();  
        this.setTitle("Registro del historial de los pacientes");
       // CargarHistorial();
    }

    public void llenaTabla() {
        dtmhistorial.addColumn("HISTORIA CLINICA");
        dtmhistorial.addColumn("CITA");
        dtmhistorial.addColumn("SINTOMAS");
        dtmhistorial.addColumn("TIEMPOS");
        dtmhistorial.addColumn("ENFERMEDAD");
        dtmhistorial.addColumn("TEMPERATURA");
        dtmhistorial.addColumn("FRECUENCIA CARDIACA");
        dtmhistorial.addColumn("FRECUENCIA RESPIRATORIA");
        dtmhistorial.addColumn("SATURACION");
        dtmhistorial.addColumn("ANAMNESIS");

        this.tHistorial.setModel(dtmhistorial);
    }

    public void listar() {
        dtmhistorial.setNumRows(0);
        for (int i = 0; i < histcontroller.size(); i++) {
            Object[] vec = new Object[10];
            vec[0] = histcontroller.get(i).getHistclini();
            vec[1] = histcontroller.get(i).getCita();
            vec[2] = histcontroller.get(i).getSintomas();
            vec[3] = histcontroller.get(i).getTiempos();
            vec[4] = histcontroller.get(i).getEnfermedad();
            vec[5] = histcontroller.get(i).getTemperatura();
            vec[6] = histcontroller.get(i).getFrecuenciacardi();
            vec[7] = histcontroller.get(i).getFrecuenciarespi();
            vec[8] = histcontroller.get(i).getSaturacion();
            vec[9] = histcontroller.get(i).getAnamnesis();
            dtmhistorial.addRow(vec);
        }
        tHistorial.setModel(dtmhistorial);
    }
    
    //cargar historial del paciente
    public void CargarHistorial(){
       for(int i=0;i<histcontroller.size();i++){
        histcontroller.buscar(Integer.parseInt(txth.getText()));
        }
    }

    /*public void CargarPaciente(){
        for(int i=0;i<histcontroller.size();i++){
            histcontroller.get(i).getHistclini()== Integer.parseInt(txth.getText);
        }
    }*\

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txts = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txte = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tHistorial = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtbuscardni = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txttem = new javax.swing.JTextField();
        txtfc = new javax.swing.JTextField();
        txtfr = new javax.swing.JTextField();
        txtsa = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txth = new javax.swing.JTextField();
        txtc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtshowname = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(775, 600));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Historial de pacientes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Historia Clínica");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Sintomas");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Tiempo de sintomas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("Anamnesis");

        tHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tHistorial);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("Enfermedad");

        jLabel7.setText("Buscar Por DNI");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("Temperatura");

        txtbuscardni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscardniActionPerformed(evt);
            }
        });
        txtbuscardni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscardniKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setText("Frecuencia cardíaca");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setText("Frecuencia respiratoria");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setText("Saturación");

        btnregistrar.setText("Registar");
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnregistrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnregistrarMouseReleased(evt);
            }
        });
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btneditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btneditarMouseReleased(evt);
            }
        });
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btncerrar.setText("Cerrar");
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btncerrarMouseReleased(evt);
            }
        });
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnbuscarMouseReleased(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Cita");

        txth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthActionPerformed(evt);
            }
        });

        txtshowname.setColumns(20);
        txtshowname.setRows(5);
        jScrollPane2.setViewportView(txtshowname);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfr, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbuscardni, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel20)
                    .addComponent(txttem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22)
                    .addComponent(txtfr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneditar)
                            .addComponent(btnregistrar)
                            .addComponent(btncerrar)
                            .addComponent(btnbuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscardni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        int msg = JOptionPane.showConfirmDialog(this, "Deseas Registrar la información", "Registrar", JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION) {

            Historialc hist = new Historialc() {
            };
            hist.setHistclini(Integer.parseInt(this.txtc.getText()));
            hist.setCita(Integer.parseInt(this.txtc.getText()));
            hist.setSintomas(this.txts.getText());
            hist.setTiempos(Integer.parseInt(this.txtt.getText()));
            hist.setEnfermedad(this.txte.getText());
            hist.setTemperatura(Double.parseDouble(this.txttem.getText()));
            hist.setFrecuenciacardi(Integer.parseInt(this.txtfc.getText()));
            hist.setFrecuenciarespi(Integer.parseInt(this.txtfr.getText()));
            hist.setSaturacion(Integer.parseInt(this.txtsa.getText()));
            hist.setAnamnesis(this.txta.getText());

            //Insertar el objeto al arreglo
            histcontroller.add(hist);

            histcontroller.grabar(); //METODO DE GRABAR en controller "semana 11"
            listar();

            JOptionPane.showMessageDialog(this, "Datos registrados satisfactoriamente!!!");
            bloquear_controles();
            btneditar.setEnabled(true);  //habilitad el boton editar
        } else {
            txtc.requestFocus();
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        int msg = JOptionPane.showConfirmDialog(this, "Deseas modificar el registro", "Modificar", JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION) {
            Historialc hist = histcontroller.buscar(Integer.parseInt(txth.getText()));
            if (hist != null) {  //si pro es diferente de null

                //Modificadores
                hist.setCita(Integer.parseInt(this.txtc.getText()));
                hist.setSintomas(this.txts.getText());
                hist.setTiempos(Integer.parseInt(this.txtt.getText()));
                hist.setEnfermedad(this.txte.getText());
                hist.setTemperatura(Double.parseDouble(this.txttem.getText()));
                hist.setFrecuenciacardi(Integer.parseInt(this.txtfc.getText()));
                hist.setFrecuenciarespi(Integer.parseInt(this.txtfr.getText()));
                hist.setSaturacion(Integer.parseInt(this.txtsa.getText()));
                hist.setAnamnesis(this.txta.getText());

                //para actualizar se llama al metodo listar
                listar();

                histcontroller.grabar();
                JOptionPane.showMessageDialog(this, "Registro actualizado satisfactoriamente");

            } else {
                JOptionPane.showMessageDialog(this, "Objeto no encontrado");
            }
        }


    }//GEN-LAST:event_btneditarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed
    
    
    int codhistorial;
    
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
       if(pacicontroller.buscar2(Integer.parseInt(txtbuscardni.getText()))!= null){
        Paciente objpaci = pacicontroller.buscar2(Integer.parseInt(txtbuscardni.getText()));
//        if(objpaci!= null){
//        //codhistorial = objpaci.getDni();        
        this.txth.setText("" + objpaci.getHistclini());
        this.txtshowname.setText("Nombre y Apellido del paciente: " + "\n" + objpaci.getNomape());

     }
     else{
           
      JOptionPane.showMessageDialog(this, "Paciente no encontrado");


     }

               
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscardniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscardniKeyReleased

    }//GEN-LAST:event_txtbuscardniKeyReleased

    private void txtbuscardniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscardniActionPerformed

    }//GEN-LAST:event_txtbuscardniActionPerformed

    private void txthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthActionPerformed

    }//GEN-LAST:event_txthActionPerformed

    private void btnregistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMousePressed
        btnregistrar.setBackground(Color.CYAN);    
    }//GEN-LAST:event_btnregistrarMousePressed

    private void btnregistrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseReleased
        btnregistrar.setBackground(Color.WHITE);        
    }//GEN-LAST:event_btnregistrarMouseReleased

    private void btneditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMousePressed
        btneditar.setBackground(Color.CYAN);  
    }//GEN-LAST:event_btneditarMousePressed

    private void btneditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMouseReleased
        btneditar.setBackground( Color.WHITE);  
    }//GEN-LAST:event_btneditarMouseReleased

    private void btncerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMousePressed
        btncerrar.setBackground( Color.ORANGE);    
    }//GEN-LAST:event_btncerrarMousePressed

    private void btncerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseReleased
        btncerrar.setBackground( Color.WHITE);    
    }//GEN-LAST:event_btncerrarMouseReleased

    private void btnbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMousePressed
        btnbuscar.setBackground( Color.MAGENTA);    
    }//GEN-LAST:event_btnbuscarMousePressed

    private void btnbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseReleased
        btnbuscar.setBackground( Color.WHITE);
    }//GEN-LAST:event_btnbuscarMouseReleased

    public void limpiar() {

        this.txtc.setText("");
        this.txts.setText("");
        this.txtt.setText("");
        this.txte.setText("");
        this.txttem.setText("");
        this.txtfc.setText("");
        this.txtfr.setText("");
        this.txtsa.setText("");
        this.txta.setText("");
    }

    public void bloquear_controles() {
        btnbuscar.setEnabled(true);

        btnregistrar.setEnabled(false);
        btneditar.setEnabled(false);
    }

    public void activar_controles() {
        btnbuscar.setEnabled(true);

        btnregistrar.setEnabled(true);
        btneditar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tHistorial;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtbuscardni;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtfc;
    private javax.swing.JTextField txtfr;
    private javax.swing.JTextField txth;
    private javax.swing.JTextField txts;
    private javax.swing.JTextField txtsa;
    private javax.swing.JTextArea txtshowname;
    private javax.swing.JTextField txtt;
    private javax.swing.JTextField txttem;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondoD.jpeg")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
